server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: ${HS_USER_EUREKA_URI:localhost:8654}

spring:
  datasource:
    url: jdbc:postgresql://${HS_USER_DATASOURCE_HOST}:${HS_USER_DATASOURCE_PORT}/${HS_USER_DATASOURCE_DATABASE}
    username: ${HS_USER_DATASOURCE_USERNAME}
    password: ${HS_USER_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true

application:
  security:
    jwt:
      secret-key: ${HS_USER_JWT_SECRET_KEY}
      expiration: ${HS_USER_JWT_EXPIRATION}


springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

management:
  endpoints:
    web:
      exposure:
        include: "*"
